### ISSUE TITLE
Not able to focus and unmute after meeting started?

### ISSUE THREAD

**Issue by sbelmon** [vapier/chrome-ext-goat-meet-manager#1]
I didn't dig, but I think that the mute/unmute on icon click doesn't work anymore -- not once you've joined the meeting?
Wild guess -- due to the messy changes they made, making that in-call UI all busy and full of buttons?

**Comment by vapier** [comment]
yeah, the UI refresh keeps throwing things off.  i fixed it after the first one, but the most recent update broke it again.

atm it's probing based on (compiled) class names as the objects don't have unique ids.  maybe i can try using other metadata as a proxy as a fallback (like some of the alt text).

**Comment by vapier** [comment]
i submitted a v0.8 to the CWS that should hopefully fix things again.  it can take ~24hrs for the CWS to approve & start pushing to users.
